version: "3.5"

services:
  api1: &api
    build: .
    # TODO: ghcr
    hostname: api1
    environment:
      - DB_HOSTNAME=db
      - DB_PASSWORD=pass
      - DB_USER=admin
      - DB_DB=rinha
    
    ports:
      - "8081:80"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

#   api2:
#     # Essa sintaxe reusa o que foi declarado em 'api1'.
#     <<: *api 
#     hostname: api2
#     environment:
#       - DB_HOSTNAME=db
#       - DB_PASSWORD=pass
#       - DB_USER=admin
#       - DB_DB=rinha
#     ports:
#       - "8082:8080"
 
  load_balancer:
    image: haproxy:latest
    volumes:
      - type: bind
        source: ./haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
    depends_on:
      - api1
      - api2
    ports:
      - "9999:80" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./db.sql
        target: /docker-entrypoint-initdb.d/db.sql
        read_only: true
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

# networks:
#   default:
#     driver: bridge
#     name: rinha-2024q1
